### ISSUE TITLE
Any way to show profile cover like facebook?

### ISSUE THREAD

**Issue by ghost** [ColdTrick/profile_cover#2]
It only allows uploading cover photo.
Is there any plan to implement cover photo like facebook?
Thanks

**Comment by jeabakker** [comment]
As stated in the readme of the plugin displaying the profile cover needs to be implemented within your theme. 
So no there are no plans to display it by default, because every theme is different and the theme developer needs to implement it at their own place anyway

**Comment by ghost** [comment]
Got it. For elgg 3.x, it is quite useless then.
